# Generated by Django 3.2.8 on 2023-10-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emailattachement_id_alter_emaillog_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='send_at',
            new_name='sent_at',
        ),
        migrations.RenameField(
            model_name='emaillog',
            old_name='send_by',
            new_name='sent_by',
        ),
    ]
